### ISSUE TITLE
Prevent rerender on route change

### ISSUE THREAD

**Issue by uweg** [orus-io/elm-spa#10]
Is there a way to prevent calling the ```init``` function when the route changes (to the same page)?

Something like sending a ```FlagsChanged``` message when the route is same with different flags.

Use case would be a search field that reflects its state in the url. Currently it reloads the page on every keystroke.

PS: Thanks for the great package!

**Comment by cdevienne** [comment]
Yes there is !

https://package.elm-lang.org/packages/orus-io/elm-spa/latest/Spa-Page#onNewFlags

PS: my pleasure ;-)

**Comment by uweg** [comment]
Thank you! Sorry for not reading the docs good enough 😉
