### ISSUE TITLE
Provide url in init

### ISSUE THREAD

**Issue by uweg** [orus-io/elm-spa#11]
I need the `Url` in the `init` function to add the current route to the shared state on page load.

I added this in a local copy of the package and it is just a minor change and works fine.

If there is a better way to do this, let me know 🙂

**Comment by cdevienne** [comment]
A simple solution would be to add the Url to the page flags.
That said, we can try to find a generic solution to get access to the current route. I am thinking of a 'onNewRoute' handler that would take a shared msg. I'll think about it.

**Comment by cdevienne** [comment]
Also, if you use directly PageStack, you can implement the page protection mechanism any way you want. But for the rare cases we needed things like that, we simply added a redirection in the page init. Way simpler to understand.

**Comment by cdevienne** [comment]
@uweg I added, in the new 'route-change' branch, a "beforeChangeRoute" function. It allows you to update the shared model before the page is loaded. For example:

```elm
-- in Shared.elm

type Msg
    = BeforeChangeRoute

update : Model -> Msg -> (Model, Cmd Msg)
update model msg =
    case msg of
        BeforeChangeRoute route ->
            ({ model | currentRoute = route }, Cmd.none)

-- in Main.elm

main =
    Spa.init -- ...
    |> Spa.beforeRouteChange Shared.BeforeRouteChange
    |> Spa.application

```

Let me know if it solves your issue.

**Comment by uweg** [comment]
This looks like it solves my issue.

I came up with a slightly different approach in my local copy but your approach is cleaner:

```elm
|> Spa.application View.map
    { toRoute = Route.toRoute
    , init = Shared.init
    , update = Shared.update
    , subscriptions = Shared.subscriptions
    , toDocument = toDocument
    , protectPage = Route.toUrl >> Just >> (\_ -> Route.Login) >> Route.toUrl
    , onUrlChange = Shared.urlChanged
    }
```

For context: I currenty use this to log page navigation and to highlight the current page in the menu.

**Comment by cdevienne** [comment]
v3.0.0 is out and contains the beforeChangeRoute function
