### ISSUE TITLE
Hidden flags

### ISSUE THREAD

**Issue by MattiaVerticchio** [orus-io/elm-spa#12]
Hi, thanks for developing this framework! 😁

I have a question about how routes handle flags.

Currently, the flags are defined in a `Route.elm` module, in which are defined the functions
```elm 
toUrl : Route -> String

route : Parser (Route -> a) a
```
that handle rendering and parsing the flags through URL parameters.

My question is: would it be possible to pass flags to each route without exposing them in the URL?

For example, protected pages can receive an `Identity` and fall back to a specified page if not provided, could that behavior be extended to generic values passed as flags?

**Comment by cdevienne** [comment]
If the flags are not coming from the URL, then from where? Probably the shared state.
If that's what you have in mind, then you don't need the flags for that, as you can pass the shared state to your page init function.
If it doesn't solve you case, could you provide an example?

**Comment by MattiaVerticchio** [comment]
Thanks for the quick reply, I’ll give you an example 😁

Let’s say I have a page that displays some product details. The products are stored in the `Shared` state as `List Product` and a product is:
```elm
type alias Product =
    { name : String
    , info : String
    , id : Int
    }
```

Currently, I could pass the `id` via URL parameters and then in the product details page manually retrieve the corresponding product from `Shared`, displaying an error if the product is not found.

My question is if it could be possible to pass the whole `Product` as a _hidden_ parameter to the route in a way similar to `Identity`. This method would avoid the error state that could come from manually adding to the URL an invalid `id`. In other words, the route would be guaranteed to have a valid `Product` to display.

If I understood correctly your suggestion, passing the data through the `Shared` state would require adding a field to represent the currently "focused" product to access from the details page.

That field however would be useful only on that route and should be updated each time a product is focused while having
```elm
Shared.PushRoute <|  Route.ProductDetails Product
```
is more practical.

Is my approach correct? I’m still learning Elm and appreciate any kind of feedback!

**Comment by cdevienne** [comment]
I would not store a current state in the shared state as you suggest, I would just wrap the init function, something like this:

```elm
init : Shared -> Int -> (Model, Effect Shared.Msg Msg)
init shared id =
    Shared.getProduct id shared
    |> Maybe.map realinit
    |> Maybe.withDefault (emptyModel, Navigation.push shared.key "/notfound")
    
realinit : Product -> (Model, Effect Shared.Msg Msg)
realinit product =
    -- ....
```

"Hidden" parameters as you name them, would be a preprocessing of the route. But the needs of such a preprocessing can vary a lot between projects, and providing a common api for that may not be simple, and I would like to keep the library as simple and small as possible.

**Comment by cdevienne** [comment]
@MattiaVerticchio I added, in the new 'route-change' branch, a "beforeChangeRoute" function. It allows you to update the shared model before the page is loaded. For example:

```elm
-- in Shared.elm

type Msg
    = BeforeChangeRoute

update : Model -> Msg -> (Model, Cmd Msg)
update model msg =
    case msg of
        BeforeChangeRoute route ->
            ({ model | currentRoute = route }, Cmd.none)

-- in Main.elm

main =
    Spa.init -- ...
    |> Spa.beforeRouteChange Shared.BeforeRouteChange
    |> Spa.application
```

Let me know if it solves some of your issues.

**Comment by MattiaVerticchio** [comment]
I understand now, thank you! 😁
