### ISSUE TITLE
elm-app-url

### ISSUE THREAD

**Issue by ericwern** [orus-io/elm-spa#15]
Hi again. Have you given any thoughts about supporting [elm-app-url](https://package.elm-lang.org/packages/lydell/elm-app-url/latest/) ?

**Comment by cdevienne** [comment]
Hi there,
Sorry for not answering, but I see you got to the right conclusion.
From what I see, using it is already possible in your route parser, and adding it at the elm-spa level would not bring anything. I'd be glad to be proven otherwise though.
Cheers
