### ISSUE TITLE
Init a specific page with url

### ISSUE THREAD

**Issue by kuglee** [orus-io/elm-spa#2]
With ryannhg's elm-spa you can go to a specific page with a url e.g. http://localhost:8000/time.
It would be nice to also have this functionality in this package.

**Comment by cdevienne** [comment]
Unless I am mistaken, you can by running your application with "elm-live --pushstate":
```
   -u, --pushstate [pushstate]      Forces the index.html or whatever filename you have passed to the --start-page flag to always be served. Must be used when building with Browser.application. (default: false)
```

**Comment by kuglee** [comment]
Oh, I didn't know about that. Thanks.
