### ISSUE TITLE
Shared view

### ISSUE THREAD

**Issue by kuglee** [orus-io/elm-spa#3]
With ryannhg's elm-spa you can create a shared view that has access to the SharedMsg and to the current route, because the Model and the Msg is in the Main module. Because these are not accessible in this package, this is currently not possible. Official support would be nice to have.

For a better understanding here's what I currently use for the time being. (I'm sure there are better ways to do his):

```Elm
application :
    { toDocument : shared -> view -> Document (Msg sharedMsg pageMsg)
    , sharedView : Maybe ((sharedMsg -> Msg sharedMsg pageMsg) -> route -> shared -> view -> view)
    }
    -> Builder flags route identity shared sharedMsg view current previous pageMsg
    ->
        { init : flags -> Url -> Nav.Key -> ( Model route shared current previous, Cmd (Msg sharedMsg pageMsg) )
        , view : Model route shared current previous -> Document (Msg sharedMsg pageMsg)
        , update : Msg sharedMsg pageMsg -> Model route shared current previous -> ( Model route shared current previous, Cmd (Msg sharedMsg pageMsg) )
        , subscriptions : Model route shared current previous -> Sub (Msg sharedMsg pageMsg)
        , onUrlRequest : UrlRequest -> Msg sharedMsg pageMsg
        , onUrlChange : Url -> Msg sharedMsg pageMsg
        }
application { toDocument, sharedView } builder =
    let
        view_ =
            case sharedView of
                Just sharedView_ ->
                    \model -> builder.view model |> (\view -> toDocument (modelShared model) (sharedView_ SharedMsg (modelRoute model) (modelShared model) view))

                Nothing ->
                    \model -> builder.view model |> toDocument (modelShared model)
    in
    { init = builder.init
    , view = view_
    , update = builder.update
    , subscriptions = builder.subscriptions
    , onUrlRequest = UrlRequest
    , onUrlChange = UrlChange
    }


modelRoute : Model route shared current previous -> route
modelRoute ( core, _ ) =
    core.currentRoute
```

**Comment by cdevienne** [comment]
Using shared msg in a view can be done by adding a 'SharedMsg' in the page and relay it with a Effect.shared in the page update.
It is a little inconvenient but works and is a good workaround until we find a proper way to do it.

For accessing the current route we need to change the api, and I see 2 possible approaches:

### Pass the current route to all the views

The pages can then use a shared view function to build the common parts. Something like:
   ```elm
   view : Route -> Shared -> Model -> View Msg
   view route shared model =
       sharedView SharedMsg route shared <| pagebody model
   ```
It is consistent with the current way of using shared msg in page views, that I described earlier. But it also implies that the pages have a knowledge of the Route type, which I avoided for the init function. Not sure we want to avoid it for the views.

### Pass a 'SharedMsg' and the current route to the 'toDocument' function

It implies that most of the common parts of the views will be done in toDocument and not in the page views.
This means that if the page needs to influence the common parts in some way it must be done through the page view type, which could lead to a page view type with many things. Not sure it's a bad thing.

### What do we do ?

I have a feeling the first approach is less restrictive, as I always had the idea that 'toDocument' should only convert the page view to a browser document, and not add a bunch of things to it.

**Comment by kuglee** [comment]
Thank you for your answer and thank you for this package.

**Comment by cdevienne** [comment]
The most recent release added a "mapSharedMsg" function that allows the "toDocument" function to have inputs generating shared messages. I think it solves the current issue regarding the shared messages.
As for the current route, I am not yet convinced it's that much needed. If some information is needed by toDocument to build the general layout, it can be added to the page view.
